### PR TITLE
Feature/add 1password provider

### PR DESCRIPTION
**Pull request by kaplanelad**
Adding 1password provider. 

More Information:
1) Run (system-to-system)[https://support.1password.com/connect-deploy-docker/] secret manager
2) Create new token in 1Password
3) run `teller new` with 1Password provider
4) edit provider section with the following data
Config:
```yaml
providers:
  1password:
    env_sync:
      path: # Secret title in 1Password
      source: #{VAULTUUID}
    env:
      Note:
          path: # Secret title in 1Password
          source: #{VAULTUUID}
          field: # field in secret (notesPlain, {custom label name}, password, type etc).
```
4) Read:
```sh
OP_CONNECT_HOST="http://localhost:8080"  OP_CONNECT_TOKEN="" go run main.go show
```
5) Update:
```sh
OP_CONNECT_HOST="http://localhost:8080"  OP_CONNECT_TOKEN="" go run main.go put Note=newVal --providers 1password
```

Test:
Generate 1Password client: 
```sh
mockgen -source pkg/providers/onepassword.go -destination pkg/providers/mock_providers/onepassword_mock.go
```

### CODE REVIEW

**Comment by kaplanelad** [comment]
Hey, 
there is also requested issue #10 for adding this provider

**Comment by pentago** [comment]
I don't see 1Pasword provider, was it removed at some point?

**Comment by kaplanelad** [comment]
Hey @pentago, in v2.x password is not supported yet by our providers. 
you can see the supported providers here: https://docs.rs/teller-providers/2.0.7/teller_providers/providers/index.html

1password is in our list and we will add it

**Comment by mschirrmeister** [comment]
@pentago It looks like a few month ago was a commit `teller ng` where the project (I guess) switched from **go** to **rust**. Not sure, but maybe there was a complete rewrite. Hope what was there before in terms of providers will come back sooner than later.

I use for now the **1Password-CLI** tool `op` to get items either from 1P directly or from the 1p-connect-server.

**Pull request merged**
